[build]:
  command: "npm run build"
  commandOrigin: config
  publish: /opt/build/repo/out

  [functions]:
  '*': {}

 [[plugins]]:
  - inputs: {}
  origin: config
  package: '@netlify/plugin-nextjs'
